version: '3.4'
services:
  main:
    build:
      context: "./../src"
    image: "firefox-syncserver-local"
    container_name: firefox-syncserver
    volumes:
      - ./../data:/data
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - "VIRTUAL_PORT=5000"
      - SYNCSERVER_PUBLIC_URL=https://${VIRTUAL_HOST}
      - SYNCSERVER_SECRET=${SYNCSERVER_SECRET}
      - SYNCSERVER_SQLURI=sqlite:////data/syncserver.db
      - SYNCSERVER_BATCH_UPLOAD_ENABLED=true
      - SYNCSERVER_FORCE_WSGI_ENVIRON=true
      - PORT=5000
    restart: "unless-stopped"
    expose:
      - 5000
    networks:
      - nginx-proxy

volumes:
  data:

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
